#
#mybatis.config-location=classpath:/mybatis/mybatis-config.xml
#type-aliases-package=com.lzw.monitor
#mybatis.mapper-locations=classpath:mapper/*.xml
## 数据库访问配置，
## 主数据源，默认的
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
## 下面为连接池的补充设置，应用到上面所有数据源中
## 初始化大小，最小，最大
#spring.datasource.initialSize=5
#spring.datasource.minIdle=5
#spring.datasource.maxActive=20
## 配置获取连接等待超时的时间
#spring.datasource.maxWait=60000
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#spring.datasource.timeBetweenEvictionRunsMillis=60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#spring.datasource.minEvictableIdleTimeMillis=300000
## Oracle请使用select 1 from dual
#spring.datasource.validationQuery=SELECT 'x'
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
## 打开PSCache，并且指定每个连接上PSCache的大小
#spring.datasource.poolPreparedStatements=true
#spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#spring.datasource.filters=stat,wall,slf4j
## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
## 合并多个DruidDataSource的监控数据
#spring.datasource.useGlobalDataSourceStat=true

#management.endpoints.web.exposure.include=*
#debug=true
#envirment.label = prod

---

server:
  port: 9090

spring:
  application:
    name: spring-boot-lzw
  datasource:
# 从主数据库配置
    slaver:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-2ze61897o1ab3go6npo.mysql.rds.aliyuncs.com:3306/wanmi_monitor?useSSL=false
      username: root
      password: Pusi@2014
# 主数据库配置
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-2ze61897o1ab3go6npo.mysql.rds.aliyuncs.com:3306/wanmi_uat_monitor?useSSL=false
      username: root
      password: Pusi@2014



#    druid:
#      initial-size: 5
#      min-idle: 3
#      max-active: 5
#      max-wait: 1000




debug: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  ## 默认为simple 批量的程序建议改成batch
  executor-type: simple
  type-aliases-package: com.lzw.monitor.model

  master:
    mapper-locations: classpath:mastermapper/*Mapper.xml
    executor-type: simple
    type-aliases-package: com.lzw.monitor.model
logging:
  level:
    com.lzw.*.dao: debug


